<center><b><font size="+3" color="#340DF8">Student Development Programme</font></b><br><br></center>
<font size="+1">We have a lot of emphasis on the continuous growth and all round development of our students through training and several other activities to make the students placeable. We offer regular training inputs and help them learn and acquire new skills and competencies through various activities such as industrial tours, mock interviews, group discussions, aptitude tests, expert lectures etc. </font>



•	Entrepreneurship Awareness CellThe college encourages the students to start their own enterprises after completion of their course. In this context the college is having an Entrepreneurship Awareness Cell. Through this cell the college arranges three days training every year for the students who wish to become entrepreneurs after completion of their course. Entrepreneuship Development of India, New Delhi, also helps this cell in delivering the lectures by their faculties. <br>
1.	Industrial Tour: A technical course is incomplete without exposure of the student to industry. Hence college arranges educational tours for the students on a regular basis. The intricacies of theory and field are explained by the industry experts during their visits. The theory taught in classroom is made clear during these visits.<br>
2.Online Logical Reasoning Tests: Students of EQUINOX Committee conducts online tests twice a month. These tests are designed for students of all courses. The pattern of the test is similar to the online tests which are conducted by the companies. These tests are organized by the Training and Placement Cell of the College. We also organize online training in collaboration with Aspiring Minds and MeritTrac (GBTU WATCH).<br>
3.Group Discussion: Presentation skill is necessary part of the interviews now a days. With this objective group discussion forms a regular feature whereby students, in a group of 6-8 are encouraged to discuss various topics related to their field and also of current affairs.<br>
4.Mock Interviews: The Training and Placement Cell ensures that the students are completely prepared and are confident before appearing for the interviews in the companies. The aim of the exercise is to help students in grooming their overall personality and bringing out the hiddedn talents, creativity and flair of the students.<br>
5.Industrial Training:In order to give hands-on experience of thecorporate world, industrial training after the pre-final year has been made a part of the curriculum. We have established a proactive industry involvement program for arranging industrial training and internships. MBA students have to undergo training for 4 weeks (after II Sem), B.Tech and B.Pharma Students have to undergo training for 4 to 6 weeks (after VI Sem.). The members of the placement cell arrange for personal feedback of the students from the organizations which are providing them training whereby faculty representatives go and meed the trainers personally and enquire about student's performance.<br>
6.Final Placement: For the final placement of the students the placement cell arranges on campus and off-campus placement process. The emerging trends in the global markets are monitored and programmed are organized to provide latest skill and competencies required by the industries. The college boasts of excellent placement record with most of our students getting placement in good companies.<br>
</font>
